name: 🌴 Generate TOC
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/toc-generator@v2
        with:
          TOC_TITLE: "## Table of Contents"